name: health_quiz_app
description: "A new Flutter project."
publish_to: "none"

version: 0.8.3+83

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter # ← これを追加
  intl: ^0.20.2 # （任意。日付/数値の整形に便利）
  provider: ^6.1.2
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  csv: ^6.0.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  crypto: ^3.0.3 # ←★これを追加
  uuid: ^4.4.0
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.0
  in_app_purchase: ^3.2.3
  device_info_plus: ^12.2.0
  flutter_local_notifications: ^19.0.0
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/decks/
    - assets/images/
  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Regular.ttf
        - asset: assets/fonts/NotoSansJP-Bold.ttf
          weight: 700

flutter_native_splash:
  color: "#F7FAF4" # 背景色（今の淡いアイボリー等に合わせて）
  color_dark: "#0b0f0c" # ダーク時（任意）
  image: assets/images/splash_logo.png
  image_dark: assets/images/splash_logo.png
  android_12:
    color: "#F7FAF4"
    icon_background_color: "#F7FAF4"
    image: assets/images/splash_logo.png
  android: true
  ios: true
  web: false

flutter_launcher_icons:
  android: true
  ios: true

  image_path_android: "assets/images/foreground.png"
  image_path_ios: "assets/images/foreground.png" # ← ここを変更

  adaptive_icon_foreground: "assets/images/foreground.png"
  adaptive_icon_background: "#3F5E44"
  adaptive_icon_monochrome: "assets/images/monochrome.png"

  remove_alpha_ios: false

  macos:
    generate: true
    image_path: "assets/images/foreground.png"
    remove_alpha: false
